version: '3'

networks:
  app:
    driver: bridge

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - app
    restart: unless-stopped

volumes:
  postgres:
